@echo off
echo ========================================
echo EST Framework Full Test Suite
echo ========================================
echo.

echo Compiling test runner...
javac -cp "target/classes;est-base/est-test/est-test-api/target/classes;est-base/est-test/est-test-impl/target/classes;est-core/est-core-container/est-core-container-api/target/classes;est-core/est-core-container/est-core-container-impl/target/classes;est-core/est-core-config/est-core-config-api/target/classes;est-core/est-core-config/est-core-config-impl/target/classes;est-base/est-patterns/est-patterns-api/target/classes;est-base/est-patterns/est-patterns-impl/target/classes;est-base/est-collection/est-collection-api/target/classes;est-base/est-collection/est-collection-impl/target/classes;est-base/est-utils/est-util-common/target/classes;est-modules/est-foundation/est-event/est-event-api/target/classes;est-modules/est-foundation/est-event/est-event-local/target/classes;est-modules/est-foundation/est-cache/est-cache-api/target/classes;est-modules/est-foundation/est-cache/est-cache-memory/target/classes;est-modules/est-data-group/est-workflow/est-workflow-api/target/classes;est-modules/est-data-group/est-workflow/est-workflow-core/target/classes;est-app/est-admin/est-admin-api/target/classes;est-app/est-admin/est-admin-impl/target/classes;est-modules/est-ai-suite/est-ai-assistant/est-ai-api/target/classes;est-modules/est-ai-suite/est-ai-assistant/est-ai-impl/target/classes;est-modules/est-ai-suite/est-rag/est-rag-api/target/classes;est-modules/est-ai-suite/est-rag/est-rag-impl/target/classes;est-modules/est-extensions/est-plugin-marketplace/est-plugin-marketplace-api/target/classes;est-modules/est-extensions/est-plugin-marketplace/est-plugin-marketplace-impl/target/classes;est-modules/est-integration-group/est-observability/est-observability-api/target/classes;est-modules/est-microservices/est-grpc/est-grpc-api/target/classes;est-modules/est-microservices/est-grpc/est-grpc-core/target/classes;est-modules/est-security-group/est-multitenancy/est-multitenancy-api/target/classes;est-modules/est-security-group/est-multitenancy/est-multitenancy-impl/target/classes;est-modules/est-cloud-group/est-serverless/est-serverless-api/target/classes;est-modules/est-foundation/est-config/est-config-api/target/classes;est-modules/est-foundation/est-config/est-config-impl/target/classes;est-modules/est-web-group/est-gateway/est-gateway-api/target/classes;est-modules/est-web-group/est-gateway/est-gateway-impl/target/classes;est-modules/est-foundation/est-tracing/est-tracing-api/target/classes;est-modules/est-foundation/est-tracing/est-tracing-impl/target/classes;est-core/est-core-lifecycle/est-core-lifecycle-api/target/classes;est-core/est-core-lifecycle/est-core-lifecycle-impl/target/classes;est-core/est-core-aop/est-core-aop-api/target/classes;est-core/est-core-aop/est-core-aop-impl/target/classes;est-core/est-core-module/est-core-module-api/target/classes;est-core/est-core-module/est-core-module-impl/target/classes" RunESTTests.java

if %errorlevel% neq 0 (
    echo Compilation failed!
    exit /b 1
)

echo.
echo Running tests...
echo.
java -cp ".;target/classes;est-base/est-test/est-test-api/target/classes;est-base/est-test/est-test-impl/target/classes;est-core/est-core-container/est-core-container-api/target/classes;est-core/est-core-container/est-core-container-impl/target/classes;est-core/est-core-config/est-core-config-api/target/classes;est-core/est-core-config/est-core-config-impl/target/classes;est-base/est-patterns/est-patterns-api/target/classes;est-base/est-patterns/est-patterns-impl/target/classes;est-base/est-collection/est-collection-api/target/classes;est-base/est-collection/est-collection-impl/target/classes;est-base/est-utils/est-util-common/target/classes;est-modules/est-foundation/est-event/est-event-api/target/classes;est-modules/est-foundation/est-event/est-event-local/target/classes;est-modules/est-foundation/est-cache/est-cache-api/target/classes;est-modules/est-foundation/est-cache/est-cache-memory/target/classes;est-modules/est-data-group/est-workflow/est-workflow-api/target/classes;est-modules/est-data-group/est-workflow/est-workflow-core/target/classes;est-app/est-admin/est-admin-api/target/classes;est-app/est-admin/est-admin-impl/target/classes;est-modules/est-ai-suite/est-ai-assistant/est-ai-api/target/classes;est-modules/est-ai-suite/est-ai-assistant/est-ai-impl/target/classes;est-modules/est-ai-suite/est-rag/est-rag-api/target/classes;est-modules/est-ai-suite/est-rag/est-rag-impl/target/classes;est-modules/est-extensions/est-plugin-marketplace/est-plugin-marketplace-api/target/classes;est-modules/est-extensions/est-plugin-marketplace/est-plugin-marketplace-impl/target/classes;est-modules/est-integration-group/est-observability/est-observability-api/target/classes;est-modules/est-microservices/est-grpc/est-grpc-api/target/classes;est-modules/est-microservices/est-grpc/est-grpc-core/target/classes;est-modules/est-security-group/est-multitenancy/est-multitenancy-api/target/classes;est-modules/est-security-group/est-multitenancy/est-multitenancy-impl/target/classes;est-modules/est-cloud-group/est-serverless/est-serverless-api/target/classes;est-modules/est-foundation/est-config/est-config-api/target/classes;est-modules/est-foundation/est-config/est-config-impl/target/classes;est-modules/est-web-group/est-gateway/est-gateway-api/target/classes;est-modules/est-web-group/est-gateway/est-gateway-impl/target/classes;est-modules/est-foundation/est-tracing/est-tracing-api/target/classes;est-modules/est-foundation/est-tracing/est-tracing-impl/target/classes;est-core/est-core-lifecycle/est-core-lifecycle-api/target/classes;est-core/est-core-lifecycle/est-core-lifecycle-impl/target/classes;est-core/est-core-aop/est-core-aop-api/target/classes;est-core/est-core-aop/est-core-aop-impl/target/classes;est-core/est-core-module/est-core-module-api/target/classes;est-core/est-core-module/est-core-module-impl/target/classes" RunESTTests

echo.
echo ========================================
echo Test execution completed!
echo ========================================
