apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: est-web-app-pdb
  namespace: est
  labels:
    app: est-web-app
    app.kubernetes.io/name: est-web-app
    app.kubernetes.io/instance: est-web-app
    app.kubernetes.io/version: "1.3.0"
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: est-framework
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: est-web-app
