apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: est-demo-pdb
  namespace: est
  labels:
    app: est-demo
    app.kubernetes.io/name: est-demo
    app.kubernetes.io/instance: est-demo
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: est-framework
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: est-demo
