package ltd.idcu.est.examples.features;

import ltd.idcu.est.data.api.*;
import ltd.idcu.est.data.memory.MemoryData;
import ltd.idcu.est.data.memory.MemoryOrm;
import ltd.idcu.est.logging.api.Logger;
import ltd.idcu.est.logging.console.ConsoleLogs;

import java.util.Arrays;
import java.util.List;

public class EnhancedDataExample {

    private static final Logger logger = ConsoleLogs.getLogger(EnhancedDataExample.class);

    public static void main(String[] args) {
        System.out.println("=".repeat(70));
        System.out.println("EST Data Access Module - Enhanced Features Example");
        System.out.println("=".repeat(70));
        
        System.out.println("\nThis example will demonstrate enhanced features of EST ORM:");
        System.out.println("  - Chain query calls");
        System.out.println("  - Lambda expression queries");
        System.out.println("  - Pagination queries");
        System.out.println("  - Batch operations");
        System.out.println("  - Type-safe query building");
        System.out.println();
        
        Orm orm = new MemoryOrm();
        
        basicChainQueryExample(orm);
        lambdaQueryExample(orm);
        updateWrapperExample(orm);
        paginationExample(orm);
        batchOperationsExample(orm);
        
        System.out.println("\n".repeat(2));
        System.out.println("=".repeat(70));
        System.out.println("[X] All enhanced features examples completed!");
        System.out.println("=".repeat(70));
    }

    @Entity(tableName = "users")
    public static class User {
        @Id(autoGenerated = true)
        private Long id;
        private String name;
        private Integer age;
        private String email;
        private Double salary;
        private String department;
        
        public User() {}
        
        public User(String name, Integer age, String email, Double salary, String department) {
            this.name = name;
            this.age = age;
            this.email = email;
            this.salary = salary;
            this.department = department;
        }
        
        public Long getId() { return id; }
        public void setId(Long id) { this.id = id; }
        public String getName() { return name; }
        public void setName(String name) { this.name = name; }
        public Integer getAge() { return age; }
        public void setAge(Integer age) { this.age = age; }
        public String getEmail() { return email; }
        public void setEmail(String email) { this.email = email; }
        public Double getSalary() { return salary; }
        public void setSalary(Double salary) { this.salary = salary; }
        public String getDepartment() { return department; }
        public void setDepartment(String department) { this.department = department; }
        
        @Override
        public String toString() {
            return "User{id=" + id + ", name='" + name + "', age=" + age + 
                   ", email='" + email + "', salary=" + salary + 
                   ", department='" + department + "'}";
        }
    }

    private static void prepareTestData(Orm orm) {
        System.out.println("\n--- Preparing Test Data ---");
        
        List<User> users = Arrays.asList(
            new User("Zhang San", 28, "zhang@example.com", 15000.0, "Engineering"),
            new User("Li Si", 32, "li@example.com", 18000.0, "Engineering"),
            new User("Wang Wu", 25, "wang@example.com", 12000.0, "Product"),
            new User("Zhao Liu", 35, "zhao@example.com", 22000.0, "Product"),
            new User("Qian Qi", 30, "qian@example.com", 16000.0, "Marketing"),
            new User("Sun Ba", 27, "sun@example.com", 14000.0, "Marketing"),
            new User("Zhou Jiu", 33, "zhou@example.com", 20000.0, "Engineering"),
            new User("Wu Shi", 29, "wu@example.com", 17000.0, "Product")
        );
        
        orm.saveBatch(users);
        System.out.println("   Inserted " + users.size() + " users");
    }

    private static void basicChainQueryExample(Orm orm) {
        System.out.println("\n--- Method 1: Basic Chain Query ---");
        System.out.println("\n[Features]:");
        System.out.println("  - Concise chain call syntax");
        System.out.println("  - Supports multiple condition combinations");
        System.out.println("  - Supports sorting, pagination, etc.\n");
        
        prepareTestData(orm);
        
        System.out.println("Example 1: Query all users in Engineering department");
        List<User> techUsers = orm.query(User.class)
                .eq("department", "Engineering")
                .orderByDesc("salary")
                .get();
        System.out.println("   Results:");
        for (User user : techUsers) {
            System.out.println("     - " + user);
        }
        
        System.out.println("\nExample 2: Query users older than 30 with salary > 18000");
        List<User> highSalaryUsers = orm.query(User.class)
                .gt("age", 30)
                .and()
                .gt("salary", 18000.0)
                .get();
        System.out.println("   Results:");
        for (User user : highSalaryUsers) {
            System.out.println("     - " + user);
        }
        
        System.out.println("\nExample 3: Query users with name containing \"Zhang\"");
        List<User> zhangUsers = orm.query(User.class)
                .like("name", "Zhang")
                .get();
        System.out.println("   Results:");
        for (User user : zhangUsers) {
            System.out.println("     - " + user);
        }
        
        System.out.println("\nExample 4: Query single user");
        User firstUser = orm.query(User.class)
                .orderByAsc("age")
                .getOne();
        System.out.println("   Youngest user: " + firstUser);
        
        System.out.println("\nExample 5: Count users in Engineering department");
        long techCount = orm.query(User.class)
                .eq("department", "Engineering")
                .count();
        System.out.println("   Engineering department count: " + techCount);
        
        System.out.println("\nExample 6: Query max salary in Engineering");
        Object maxSalary = orm.query(User.class)
                .eq("department", "Engineering")
                .max("salary");
        System.out.println("   Engineering max salary: " + maxSalary);
        
        logger.info("Basic chain query example completed");
    }

    private static void lambdaQueryExample(Orm orm) {
        System.out.println("\n--- Method 2: Lambda Expression Query (Type-safe) ---");
        System.out.println("\n[Features]:");
        System.out.println("  - Type-safe, compile-time checking");
        System.out.println("  - Uses method references, avoids spelling errors");
        System.out.println("  - IDE auto-complete support");
        System.out.println("  - Safer refactoring\n");
        
        System.out.println("Note: MemoryOrm does not support Lambda queries yet, below is example code for JDBC mode");
        System.out.println("\nExample code (JDBC mode):");
        System.out.println("   // Query users in Engineering with salary > 15000, sorted by salary descending");
        System.out.println("   List<User> users = orm.lambdaQuery(User.class)");
        System.out.println("           .eq(User::getDepartment, \"Engineering\")");
        System.out.println("           .gt(User::getSalary, 15000.0)");
        System.out.println("           .orderByDesc(User::getSalary)");
        System.out.println("           .get();");
        System.out.println();
        System.out.println("   // Query single user");
        System.out.println("   User user = orm.lambdaQuery(User.class)");
        System.out.println("           .eq(User::getName, \"Zhang San\")");
        System.out.println("           .getOne();");
        System.out.println();
        System.out.println("   // Count Product department users");
        System.out.println("   long count = orm.lambdaQuery(User.class)");
        System.out.println("           .eq(User::getDepartment, \"Product\")");
        System.out.println("           .count();");
        
        logger.info("Lambda query example completed");
    }

    private static void updateWrapperExample(Orm orm) {
        System.out.println("\n--- Method 3: UpdateWrapper Updates ---");
        System.out.println("\n[Features]:");
        System.out.println("  - Flexible update conditions");
        System.out.println("  - Supports partial field updates");
        System.out.println("  - Chain calls, cleaner code\n");
        
        System.out.println("Note: MemoryOrm does not support UpdateWrapper yet, below is example code for JDBC mode");
        System.out.println("\nExample code (JDBC mode):");
        System.out.println("   // Give 10% raise to everyone in Engineering");
        System.out.println("   int updated = orm.lambdaUpdate(User.class)");
        System.out.println("           .setSql(User::getSalary, User::getSalary + \" * 1.1\")");
        System.out.println("           .eq(User::getDepartment, \"Engineering\")");
        System.out.println("           .update();");
        System.out.println();
        System.out.println("   // Update specific user's email");
        System.out.println("   int updated = orm.lambdaUpdate(User.class)");
        System.out.println("           .set(User::getEmail, \"new_email@example.com\")");
        System.out.println("           .eq(User::getName, \"Zhang San\")");
        System.out.println("           .update();");
        
        logger.info("UpdateWrapper example completed");
    }

    private static void paginationExample(Orm orm) {
        System.out.println("\n--- Method 4: Pagination Query ---");
        System.out.println("\n[Features]:");
        System.out.println("  - Auto-calculates total pages");
        System.out.println("  - Supports any query conditions");
        System.out.println("  - Returns complete pagination info\n");
        
        System.out.println("Example 1: Query page 1, 3 records per page");
        Page<User> page1 = orm.page(User.class, new Page<>(1, 3));
        System.out.println("   Page " + page1.getPageNum() + " / " + page1.getPages() + " pages");
        System.out.println("   Total records: " + page1.getTotal());
        System.out.println("   This page data:");
        for (User user : page1.getRecords()) {
            System.out.println("     - " + user);
        }
        
        System.out.println("\nExample 2: Filter by department and paginate (Engineering, page 2, 2 per page)");
        Page<User> page2 = orm.page(User.class, new Page<>(2, 2), 
                orm.query(User.class).eq("department", "Engineering"));
        System.out.println("   Page " + page2.getPageNum() + " / " + page2.getPages() + " pages");
        System.out.println("   Total records: " + page2.getTotal());
        System.out.println("   This page data:");
        for (User user : page2.getRecords()) {
            System.out.println("     - " + user);
        }
        
        logger.info("Pagination query example completed");
    }

    private static void batchOperationsExample(Orm orm) {
        System.out.println("\n--- Method 5: Batch Operations ---");
        System.out.println("\n[Features]:");
        System.out.println("  - Batch insert/update/delete");
        System.out.println("  - Reduces database interactions");
        System.out.println("  - Improves performance\n");
        
        System.out.println("Example 1: Batch insert new users");
        List<User> newUsers = Arrays.asList(
            new User("Zheng Shiyi", 26, "zheng11@example.com", 13500.0, "Engineering"),
            new User("Wang Shier", 31, "wang12@example.com", 19000.0, "Product")
        );
        List<User> savedUsers = orm.saveBatch(newUsers);
        System.out.println("   Batch inserted " + savedUsers.size() + " users");
        for (User user : savedUsers) {
            System.out.println("     - " + user);
        }
        
        System.out.println("\nExample 2: Batch update users");
        savedUsers.get(0).setSalary(14000.0);
        savedUsers.get(1).setSalary(19500.0);
        List<User> updatedUsers = orm.updateBatchById(savedUsers);
        System.out.println("   Batch updated " + updatedUsers.size() + " users");
        for (User user : updatedUsers) {
            System.out.println("     - " + user);
        }
        
        System.out.println("\nCurrent user count: " + orm.count(User.class));
        
        System.out.println("\nExample 3: Batch delete users just inserted");
        List<Object> idsToDelete = Arrays.asList(
            savedUsers.get(0).getId(),
            savedUsers.get(1).getId()
        );
        int deletedCount = orm.removeByIds(User.class, idsToDelete);
        System.out.println("   Batch deleted " + deletedCount + " users");
        
        System.out.println("\nCurrent user count: " + orm.count(User.class));
        
        logger.info("Batch operations example completed");
    }
}
