package ltd.idcu.est.examples.features;

import ltd.idcu.est.features.data.api.*;
import ltd.idcu.est.features.data.memory.MemoryData;
import ltd.idcu.est.features.data.memory.MemoryOrm;
import ltd.idcu.est.features.logging.api.Logger;
import ltd.idcu.est.features.logging.console.ConsoleLogs;

import java.util.Arrays;
import java.util.List;

public class EnhancedDataExample {

    private static final Logger logger = ConsoleLogs.getLogger(EnhancedDataExample.class);

    public static void main(String[] args) {
        System.out.println("=".repeat(70));
        System.out.println("EST 数据访问模块 - 增强功能示例（对标 MyBatis-Flex）");
        System.out.println("=".repeat(70));
        
        System.out.println("\n本示例将展示 EST ORM 的增强功能：");
        System.out.println("  - 链式调用查询");
        System.out.println("  - Lambda 表达式查询");
        System.out.println("  - 分页查询");
        System.out.println("  - 批量操作");
        System.out.println("  - 类型安全的查询构建");
        System.out.println();
        
        Orm orm = new MemoryOrm();
        
        basicChainQueryExample(orm);
        lambdaQueryExample(orm);
        updateWrapperExample(orm);
        paginationExample(orm);
        batchOperationsExample(orm);
        
        System.out.println("\n".repeat(2));
        System.out.println("=".repeat(70));
        System.out.println("✓ 所有增强功能示例完成！");
        System.out.println("=".repeat(70));
    }

    @Entity(tableName = "users")
    public static class User {
        @Id(autoGenerated = true)
        private Long id;
        private String name;
        private Integer age;
        private String email;
        private Double salary;
        private String department;
        
        public User() {}
        
        public User(String name, Integer age, String email, Double salary, String department) {
            this.name = name;
            this.age = age;
            this.email = email;
            this.salary = salary;
            this.department = department;
        }
        
        public Long getId() { return id; }
        public void setId(Long id) { this.id = id; }
        public String getName() { return name; }
        public void setName(String name) { this.name = name; }
        public Integer getAge() { return age; }
        public void setAge(Integer age) { this.age = age; }
        public String getEmail() { return email; }
        public void setEmail(String email) { this.email = email; }
        public Double getSalary() { return salary; }
        public void setSalary(Double salary) { this.salary = salary; }
        public String getDepartment() { return department; }
        public void setDepartment(String department) { this.department = department; }
        
        @Override
        public String toString() {
            return "User{id=" + id + ", name='" + name + "', age=" + age + 
                   ", email='" + email + "', salary=" + salary + 
                   ", department='" + department + "'}";
        }
    }

    private static void prepareTestData(Orm orm) {
        System.out.println("\n--- 准备测试数据 ---");
        
        List<User> users = Arrays.asList(
            new User("张三", 28, "zhang@example.com", 15000.0, "技术部"),
            new User("李四", 32, "li@example.com", 18000.0, "技术部"),
            new User("王五", 25, "wang@example.com", 12000.0, "产品部"),
            new User("赵六", 35, "zhao@example.com", 22000.0, "产品部"),
            new User("钱七", 30, "qian@example.com", 16000.0, "市场部"),
            new User("孙八", 27, "sun@example.com", 14000.0, "市场部"),
            new User("周九", 33, "zhou@example.com", 20000.0, "技术部"),
            new User("吴十", 29, "wu@example.com", 17000.0, "产品部")
        );
        
        orm.saveBatch(users);
        System.out.println("   已插入 " + users.size() + " 个用户");
    }

    private static void basicChainQueryExample(Orm orm) {
        System.out.println("\n--- 方式一：基础链式查询 ---");
        System.out.println("\n【特点】");
        System.out.println("  - 简洁的链式调用语法");
        System.out.println("  - 支持多种条件组合");
        System.out.println("  - 支持排序、分页等操作\n");
        
        prepareTestData(orm);
        
        System.out.println("示例 1: 查询技术部所有用户");
        List<User> techUsers = orm.query(User.class)
                .eq("department", "技术部")
                .orderByDesc("salary")
                .get();
        System.out.println("   结果:");
        for (User user : techUsers) {
            System.out.println("     - " + user);
        }
        
        System.out.println("\n示例 2: 查询年龄大于 30 且薪资大于 18000 的用户");
        List<User> highSalaryUsers = orm.query(User.class)
                .gt("age", 30)
                .and()
                .gt("salary", 18000.0)
                .get();
        System.out.println("   结果:");
        for (User user : highSalaryUsers) {
            System.out.println("     - " + user);
        }
        
        System.out.println("\n示例 3: 查询姓名包含 \"张\" 的用户");
        List<User> zhangUsers = orm.query(User.class)
                .like("name", "张")
                .get();
        System.out.println("   结果:");
        for (User user : zhangUsers) {
            System.out.println("     - " + user);
        }
        
        System.out.println("\n示例 4: 查询单个用户");
        User firstUser = orm.query(User.class)
                .orderByAsc("age")
                .getOne();
        System.out.println("   最年轻的用户: " + firstUser);
        
        System.out.println("\n示例 5: 统计技术部人数");
        long techCount = orm.query(User.class)
                .eq("department", "技术部")
                .count();
        System.out.println("   技术部人数: " + techCount);
        
        System.out.println("\n示例 6: 查询技术部最高薪资");
        Object maxSalary = orm.query(User.class)
                .eq("department", "技术部")
                .max("salary");
        System.out.println("   技术部最高薪资: " + maxSalary);
        
        logger.info("基础链式查询示例完成");
    }

    private static void lambdaQueryExample(Orm orm) {
        System.out.println("\n--- 方式二：Lambda 表达式查询（类型安全）---");
        System.out.println("\n【特点】");
        System.out.println("  - 类型安全，编译时检查");
        System.out.println("  - 使用方法引用，避免拼写错误");
        System.out.println("  - IDE 自动补全支持");
        System.out.println("  - 重构更安全\n");
        
        System.out.println("注意：MemoryOrm 暂不支持 Lambda 查询，以下为 JDBC 模式下的示例代码");
        System.out.println("\n示例代码（JDBC 模式）:");
        System.out.println("   // 查询技术部薪资大于 15000 的用户，按薪资降序排序");
        System.out.println("   List<User> users = orm.lambdaQuery(User.class)");
        System.out.println("           .eq(User::getDepartment, \"技术部\")");
        System.out.println("           .gt(User::getSalary, 15000.0)");
        System.out.println("           .orderByDesc(User::getSalary)");
        System.out.println("           .get();");
        System.out.println();
        System.out.println("   // 查询单个用户");
        System.out.println("   User user = orm.lambdaQuery(User.class)");
        System.out.println("           .eq(User::getName, \"张三\")");
        System.out.println("           .getOne();");
        System.out.println();
        System.out.println("   // 统计产品部人数");
        System.out.println("   long count = orm.lambdaQuery(User.class)");
        System.out.println("           .eq(User::getDepartment, \"产品部\")");
        System.out.println("           .count();");
        
        logger.info("Lambda 查询示例完成");
    }

    private static void updateWrapperExample(Orm orm) {
        System.out.println("\n--- 方式三：UpdateWrapper 更新 ---");
        System.out.println("\n【特点】");
        System.out.println("  - 灵活的更新条件");
        System.out.println("  - 支持部分字段更新");
        System.out.println("  - 链式调用，代码更清晰\n");
        
        System.out.println("注意：MemoryOrm 暂不支持 UpdateWrapper，以下为 JDBC 模式下的示例代码");
        System.out.println("\n示例代码（JDBC 模式）:");
        System.out.println("   // 给技术部所有人涨薪 10%");
        System.out.println("   int updated = orm.lambdaUpdate(User.class)");
        System.out.println("           .setSql(User::getSalary, User::getSalary + \" * 1.1\")");
        System.out.println("           .eq(User::getDepartment, \"技术部\")");
        System.out.println("           .update();");
        System.out.println();
        System.out.println("   // 更新特定用户的邮箱");
        System.out.println("   int updated = orm.lambdaUpdate(User.class)");
        System.out.println("           .set(User::getEmail, \"new_email@example.com\")");
        System.out.println("           .eq(User::getName, \"张三\")");
        System.out.println("           .update();");
        
        logger.info("UpdateWrapper 示例完成");
    }

    private static void paginationExample(Orm orm) {
        System.out.println("\n--- 方式四：分页查询 ---");
        System.out.println("\n【特点】");
        System.out.println("  - 自动计算总页数");
        System.out.println("  - 支持任意查询条件");
        System.out.println("  - 返回完整的分页信息\n");
        
        System.out.println("示例 1: 查询第 1 页，每页 3 条记录");
        Page<User> page1 = orm.page(User.class, new Page<>(1, 3));
        System.out.println("   第 " + page1.getPageNum() + " 页 / 共 " + page1.getPages() + " 页");
        System.out.println("   总记录数: " + page1.getTotal());
        System.out.println("   本页数据:");
        for (User user : page1.getRecords()) {
            System.out.println("     - " + user);
        }
        
        System.out.println("\n示例 2: 按部门筛选并分页（技术部，第 2 页，每页 2 条）");
        Page<User> page2 = orm.page(User.class, new Page<>(2, 2), 
                orm.query(User.class).eq("department", "技术部"));
        System.out.println("   第 " + page2.getPageNum() + " 页 / 共 " + page2.getPages() + " 页");
        System.out.println("   总记录数: " + page2.getTotal());
        System.out.println("   本页数据:");
        for (User user : page2.getRecords()) {
            System.out.println("     - " + user);
        }
        
        logger.info("分页查询示例完成");
    }

    private static void batchOperationsExample(Orm orm) {
        System.out.println("\n--- 方式五：批量操作 ---");
        System.out.println("\n【特点】");
        System.out.println("  - 批量插入/更新/删除");
        System.out.println("  - 减少数据库交互次数");
        System.out.println("  - 提高性能\n");
        
        System.out.println("示例 1: 批量插入新用户");
        List<User> newUsers = Arrays.asList(
            new User("郑十一", 26, "zheng11@example.com", 13500.0, "技术部"),
            new User("王十二", 31, "wang12@example.com", 19000.0, "产品部")
        );
        List<User> savedUsers = orm.saveBatch(newUsers);
        System.out.println("   批量插入了 " + savedUsers.size() + " 个用户");
        for (User user : savedUsers) {
            System.out.println("     - " + user);
        }
        
        System.out.println("\n示例 2: 批量更新用户");
        savedUsers.get(0).setSalary(14000.0);
        savedUsers.get(1).setSalary(19500.0);
        List<User> updatedUsers = orm.updateBatchById(savedUsers);
        System.out.println("   批量更新了 " + updatedUsers.size() + " 个用户");
        for (User user : updatedUsers) {
            System.out.println("     - " + user);
        }
        
        System.out.println("\n当前用户总数: " + orm.count(User.class));
        
        System.out.println("\n示例 3: 批量删除刚才插入的用户");
        List<Object> idsToDelete = Arrays.asList(
            savedUsers.get(0).getId(),
            savedUsers.get(1).getId()
        );
        int deletedCount = orm.removeByIds(User.class, idsToDelete);
        System.out.println("   批量删除了 " + deletedCount + " 个用户");
        
        System.out.println("\n当前用户总数: " + orm.count(User.class));
        
        logger.info("批量操作示例完成");
    }
}
