package ltd.idcu.est.examples.basic.data;

import ltd.idcu.est.data.api.Entity;
import ltd.idcu.est.data.api.Id;
import ltd.idcu.est.data.api.Repository;
import ltd.idcu.est.data.memory.MemoryData;

import java.util.List;

public class Data02_BasicCrud {
    public static void main(String[] args) {
        System.out.println("=== 基础篇：基本 CRUD 操作 ===\n");
        
        Repository<Product, Long> repo = MemoryData.newRepository();
        
        System.out.println("--- 1. 新增（Create�?--");
        Product p1 = new Product();
        p1.setName("iPhone 15");
        p1.setPrice(5999.0);
        p1.setStock(100);
        repo.save(p1);
        
        Product p2 = new Product();
        p2.setName("MacBook Pro");
        p2.setPrice(14999.0);
        p2.setStock(50);
        repo.save(p2);
        
        System.out.println("保存�?2 个产�?);
        
        System.out.println("\n--- 2. 查询（Read�?--");
        Product found = repo.findById(1L).orElse(null);
        System.out.println("找到 ID=1 的产品：" + found);
        
        List<Product> all = repo.findAll();
        System.out.println("所有产品：" + all);
        
        System.out.println("\n--- 3. 更新（Update�?--");
        Product toUpdate = repo.findById(1L).orElse(null);
        if (toUpdate != null) {
            toUpdate.setPrice(5499.0);
            toUpdate.setStock(80);
            repo.save(toUpdate);
            System.out.println("更新后的产品�? + repo.findById(1L).orElse(null));
        }
        
        System.out.println("\n--- 4. 删除（Delete�?--");
        repo.deleteById(2L);
        System.out.println("删除后剩余产品数�? + repo.count());
        
        repo.deleteAll();
        System.out.println("清空后剩余产品数�? + repo.count());
    }
}

@Entity
class Product {
    @Id(autoGenerated = true)
    private Long id;
    private String name;
    private double price;
    private int stock;
    
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public double getPrice() { return price; }
    public void setPrice(double price) { this.price = price; }
    public int getStock() { return stock; }
    public void setStock(int stock) { this.stock = stock; }
    
    @Override
    public String toString() {
        return "Product{id=" + id + ", name='" + name + "', price=" + price + ", stock=" + stock + "}";
    }
}
