package ltd.idcu.est.examples.basic.data;

import ltd.idcu.est.data.api.Entity;
import ltd.idcu.est.data.api.Id;
import ltd.idcu.est.data.api.Repository;
import ltd.idcu.est.data.memory.MemoryData;

public class Data01_FirstExample {
    public static void main(String[] args) {
        System.out.println("=== EST Data 第一个示�?===");
        System.out.println("这个示例将带�?分钟上手 EST Features Data！\n");
        
        Repository<User, Long> userRepository = MemoryData.newRepository();
        
        User user = new User();
        user.setName("张三");
        user.setAge(25);
        
        User savedUser = userRepository.save(user);
        System.out.println("保存的用户：" + savedUser);
        
        User foundUser = userRepository.findById(1L).orElse(null);
        System.out.println("找到的用户：" + foundUser);
        
        System.out.println("所有用户：" + userRepository.findAll());
    }
}

@Entity
class User {
    @Id(autoGenerated = true)
    private Long id;
    private String name;
    private int age;
    
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public int getAge() { return age; }
    public void setAge(int age) { this.age = age; }
    
    @Override
    public String toString() {
        return "User{id=" + id + ", name='" + name + "', age=" + age + "}";
    }
}
