package ltd.idcu.est.features.data.jdbc;

import ltd.idcu.est.features.data.api.*;

import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Field;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class CodeGenerator {
    
    private final String basePackage;
    private final String outputDir;
    
    public CodeGenerator(String basePackage, String outputDir) {
        this.basePackage = basePackage;
        this.outputDir = outputDir;
    }
    
    public void generateEntity(Class<?> entityClass) throws IOException {
        String className = entityClass.getSimpleName();
        String packageName = basePackage + ".entity";
        String filePath = outputDir + "/" + packageName.replace(".", "/") + "/" + className + ".java";
        
        StringBuilder code = new StringBuilder();
        code.append("package ").append(packageName).append(";\n\n");
        code.append("import ltd.idcu.est.features.data.api.*;\n");
        code.append("import java.time.LocalDateTime;\n\n");
        
        code.append("@Entity(tableName = \"").append(getTableName(entityClass)).append("\")\n");
        code.append("public class ").append(className).append(" {\n\n");
        
        for (Field field : entityClass.getDeclaredFields()) {
            if (field.isAnnotationPresent(Transient.class)) {
                continue;
            }
            
            if (field.isAnnotationPresent(Id.class)) {
                Id idAnnotation = field.getAnnotation(Id.class);
                code.append("    @Id(autoGenerated = ").append(idAnnotation.autoGenerated()).append(")\n");
            }
            
            Column columnAnnotation = field.getAnnotation(Column.class);
            if (columnAnnotation != null && !columnAnnotation.name().isEmpty()) {
                code.append("    @Column(name = \"").append(columnAnnotation.name()).append("\")\n");
            }
            
            if (field.isAnnotationPresent(Version.class)) {
                code.append("    @Version\n");
            }
            
            if (field.isAnnotationPresent(LogicDelete.class)) {
                LogicDelete logicDelete = field.getAnnotation(LogicDelete.class);
                code.append("    @LogicDelete(value = \"").append(logicDelete.value())
                    .append("\", notDeletedValue = \"").append(logicDelete.notDeletedValue()).append("\")\n");
            }
            
            if (field.isAnnotationPresent(CreatedAt.class)) {
                code.append("    @CreatedAt\n");
            }
            
            if (field.isAnnotationPresent(UpdatedAt.class)) {
                code.append("    @UpdatedAt\n");
            }
            
            code.append("    private ").append(field.getType().getSimpleName()).append(" ")
                .append(field.getName()).append(";\n\n");
        }
        
        for (Field field : entityClass.getDeclaredFields()) {
            if (field.isAnnotationPresent(Transient.class)) {
                continue;
            }
            
            String fieldName = field.getName();
            String capitalized = fieldName.substring(0, 1).toUpperCase() + fieldName.substring(1);
            String typeName = field.getType().getSimpleName();
            
            code.append("    public ").append(typeName).append(" get").append(capitalized).append("() {\n");
            code.append("        return ").append(fieldName).append(";\n");
            code.append("    }\n\n");
            
            code.append("    public void set").append(capitalized).append("(").append(typeName)
                .append(" ").append(fieldName).append(") {\n");
            code.append("        this.").append(fieldName).append(" = ").append(fieldName).append(";\n");
            code.append("    }\n\n");
        }
        
        code.append("}\n");
        
        writeFile(filePath, code.toString());
        System.out.println("Generated entity: " + filePath);
    }
    
    public void generateRepository(Class<?> entityClass, Class<?> idClass) throws IOException {
        String entityName = entityClass.getSimpleName();
        String repositoryName = entityName + "Repository";
        String packageName = basePackage + ".repository";
        String filePath = outputDir + "/" + packageName.replace(".", "/") + "/" + repositoryName + ".java";
        
        StringBuilder code = new StringBuilder();
        code.append("package ").append(packageName).append(";\n\n");
        code.append("import ").append(basePackage).append(".entity.").append(entityName).append(";\n");
        code.append("import ltd.idcu.est.features.data.api.Repository;\n\n");
        
        code.append("public interface ").append(repositoryName)
            .append(" extends Repository<").append(entityName).append(", ")
            .append(idClass.getSimpleName()).append("> {\n");
        code.append("}\n");
        
        writeFile(filePath, code.toString());
        System.out.println("Generated repository: " + filePath);
    }
    
    private String getTableName(Class<?> entityClass) {
        Entity entityAnnotation = entityClass.getAnnotation(Entity.class);
        if (entityAnnotation != null && !entityAnnotation.tableName().isEmpty()) {
            return entityAnnotation.tableName();
        }
        return camelToSnake(entityClass.getSimpleName());
    }
    
    private String camelToSnake(String str) {
        return str.replaceAll("([a-z])([A-Z])", "$1_$2").toLowerCase();
    }
    
    private void writeFile(String filePath, String content) throws IOException {
        java.io.File file = new java.io.File(filePath);
        file.getParentFile().mkdirs();
        try (FileWriter writer = new FileWriter(file)) {
            writer.write(content);
        }
    }
    
    public static void main(String[] args) {
        try {
            CodeGenerator generator = new CodeGenerator(
                "com.example",
                "target/generated-sources"
            );
            
            System.out.println("Code Generator ready!");
            System.out.println("Usage: generator.generateEntity(YourEntity.class);");
            System.out.println("       generator.generateRepository(YourEntity.class, Long.class);");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
