from setuptools import setup, find_packages

setup(
    name="est-framework",
    version="2.4.0",
    author="EST Team",
    author_email="team@idcu.ltd",
    description="EST Framework Python SDK - A modern Java framework with progressive module structure",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/idcu/est",
    project_urls={
        "Documentation": "https://github.com/idcu/est/docs",
        "Source": "https://github.com/idcu/est",
        "Tracker": "https://github.com/idcu/est/issues",
    },
    packages=find_packages(),
    include_package_data=True,
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Software Development :: Frameworks",
    ],
    keywords="est framework sdk plugin microservice serverless",
    python_requires=">=3.8",
    install_requires=[
        "requests>=2.28.0",
        "pydantic>=2.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-cov>=4.0.0",
            "black>=23.0.0",
            "mypy>=1.0.0",
            "setuptools>=65.0.0",
            "wheel>=0.38.0",
            "twine>=4.0.0",
        ],
    },
    zip_safe=False,
)
