package ltd.idcu.est.features.data.api;

import java.lang.annotation.*;

@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface Id {
    
    boolean autoGenerated() default true;
    
    String columnName() default "";
}
