apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: est

commonLabels:
  app.kubernetes.io/part-of: est-framework
  app.kubernetes.io/managed-by: kustomize

resources:
  - gateway.yaml
  - virtualservice.yaml
  - destinationrule.yaml
  - serviceentry.yaml
  - peerauthentication.yaml
  - authorizationpolicy.yaml
  - sidecar.yaml
